### ISSUE TITLE
Error on statusline

### ISSUE THREAD

**Issue by nishimi-ya** [fehawen/sl.vim#1]
I'm not sure what went wrong but here's the error message:
![pic-window-2020-10-26-17-59-27](https://user-images.githubusercontent.com/35223883/97164794-40e1ee80-17b5-11eb-9001-f49e550bf2fb.png)

**Comment by fehawen** [comment]
@nishinsagume Sorry, my bad. Should probably add a note that [ale](https://github.com/dense-analysis/ale) is a dependency. Just install it with Plug and things should be fine.

**Comment by nishimi-ya** [comment]
I see, thanks for the follow up.
